Die immediately on any serious error.
Formerly I was attempting to catch serious errors such as out of memory, out of
time, syntax error, or undefined symbol error, and bubble those up by returning
0.  That was wrong-headed.  It's better and vastly simpler for the code to die
immediately.

I removed all the internal checks on number of steps, amount of memory used,
and depth of stack.  Instead, I now call "ulimit" to impose limits on a Fexl
program from *outside* the code.  That also vastly simplifies the code.

The drop routine in value.c now does an eager recursive drop, instead of lazily
clearing values only when they're pulled from the free list.

I renamed "bad" as "void".  The term "void" better expresses the absence of a
value.  Also, the word "bad" slightly alarms my dog.

I moved the standard context out of fexl.c and into a separate context.c.

I eliminated "catch".  That doesn't apply any more.

I created a separate type_T so we can distinguish boolean T from C.

I don't need an is_atom function because I can just compare the types.

diff --git a/src/test/run b/src/test/run
--- a/src/test/run
+++ b/src/test/run
@@ -1,2 +1,138 @@
 #!/bin/sh
-./fexl test/a1.fxl
+./build || exit
+
+echo "== run_file test/a1.fxl"
+../bin/fexl test/a1.fxl
+echo "exit $?"
+
+echo "== run_file test/a2.fxl"
+(
+cat <<"EOF"
+abc
+defg
+
+hij
+EOF
+) \
+| ../bin/fexl test/a2.fxl
+echo "exit $?"
+
+echo "== test stderr"
+(
+cat <<"EOF"
+say "hello"
+put_to_error
+	(
+	\x=(+ 4 3)
+	say "This goes to stderr."
+	put "x = " put x nl
+	)
+say "bye"
+EOF
+) \
+| ../bin/fexl 2>&1 >/dev/null
+echo "exit $?"
+
+echo "== test parse errors"
+
+run_text()
+	{
+	echo "run_text [$text]"
+	echo -n "$text" | ../bin/fexl 2>&1
+	echo "exit $?"
+	}
+
+text="\""
+run_text
+
+text="
+\"a
+b"
+run_text
+
+text="~| a"
+run_text
+
+text="
+
+~END
+abcEN"
+run_text
+
+text="~"
+run_text
+
+text="~
+"
+run_text
+
+text="~EN"
+run_text
+
+text=" = y"
+run_text
+
+text="ab cd e\\"
+run_text
+
+text="\\x="
+run_text
+
+text="(
+a
+(b"
+run_text
+
+text="(
+a
+(b)"
+run_text
+
+text="(ab cd e)
+)"
+run_text
+
+text="x
+y
+	(z z y)
+"
+run_text
+
+echo "== test missing file"
+../bin/fexl 2>&1 missing.fxl
+echo "exit $?"
+
+# Here we test setting ulimit to terminate misbehaving programs promptly.
+test_misbehavior=false
+# To enable the test, unpound the next line.
+#test_misbehavior=true
+
+if $test_misbehavior; then
+
+echo "== test limit time"
+(
+ulimit -St 1
+text="@ I"
+run_text
+# CPU time limit exceeded
+) 2>&1
+
+echo "== test limit stack"
+(
+ulimit -Ss 1000
+text="@ @"
+run_text
+# Stack overflow (Segmentation fault)
+) 2>&1
+
+echo "== test limit memory"
+(
+ulimit -Sv 200000
+text="\S=(\x\y\z x z; y z) @ S S S"
+run_text
+# The program ran out of memory.
+) 2>&1
+
+fi
+
+exit 0
